name: vdotok_stream_example
description: Demonstrates how to use the vdotok_stream plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    # When depending on this package from a real application you should use:
    #   vdotok_stream: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  page_transition: "^2.0.5"
  flutter_statusbarcolor: ^0.2.3
  flutter_ringtone_player: ^3.2.0
  vibration: ^1.7.4-nullsafety.0
  equatable:
  shared_preferences: ^2.0.5
  http: ^0.13.4
  json_annotation: ^4.5.0
  device_info: ^2.0.0
  path_provider:
  provider: ^5.0.0
  flutter_svg: 
  audioplayers: 
  data_connection_checker: ^0.3.4
  flutter_device_type: ^0.4.0
  dart_ipify: ^1.1.1
  replay_kit_launcher: ^1.0.0
  web_socket_channel: ^2.2.0
  draggable_widget: ^2.0.0
  vdotok_stream: ^0.0.16
  move_to_background: ^1.0.2
  wakelock: ^0.5.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:
  flutter_launcher_icons: 

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_main.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Regular.ttf
    - family: Manrope
      fonts:
        - asset: fonts/Manrope/static/Manrope-Regular.ttf
    - family: Inter
      fonts:
        - asset: fonts/Inter/static/Inter-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
