name: flutter_webrtc
description: Flutter WebRTC plugin for iOS/Android/Destkop/Web, based on GoogleWebRTC.
version: 0.9.23
homepage: https://github.com/cloudwebrtc/flutter-webrtc
environment:
  sdk: ">=2.18.1 <3.0.0"
  flutter: '>=2.5.0'

dependencies:
  dart_webrtc: 1.0.15
  flutter:
    sdk: flutter
  path_provider: ^2.0.2
  webrtc_interface: 1.0.11
  simple_connection_checker: ^0.2.1
  permission_handler:

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  lints: ^2.0.0
  pedantic: ^1.11.1
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: com.cloudwebrtc.webrtc
        pluginClass: FlutterWebRTCPlugin
      ios:
        pluginClass: FlutterWebRTCPlugin
      macos:
        pluginClass: FlutterWebRTCPlugin
      windows:
        pluginClass: FlutterWebRTCPlugin
      linux:
        pluginClass: FlutterWebRTCPlugin
